use_frameworks!

platform :ios, '10.0'

target 'AppsOnAirSDK_Example' do
  pod 'AppsOnAir', :path => '../'

  target 'AppsOnAirSDK_Tests' do
    inherit! :search_paths
    
    post_install do |installer|
        installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
                end
            end
        end
    end
    
  end
end
